version: '3'

services:
  trello:
    build: client
    ports:
      - "3000:3000"
    restart: always
    environment:
      NEXT_TELEMETRY_DISABLED: 1

  api:
    build: ./API
    links:
      - db
    ports:
      - "5000:5000"
    restart: always

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
